### ISSUE TITLE
Update features/findings to reflect the API documentation

### ISSUE THREAD

**Issue by xens** [DefectDojo/Documentation#135]
When the following PR will be merged -> https://github.com/DefectDojo/django-DefectDojo/pull/2961

**Comment by madchap** [comment]
Hi @xens 

Thanks for all the contribs lately :)

So what you could do too is have the PR ready here, and we'd wait to merge it when the related feature in the main repo is merged. At your convenience.

**Comment by xens** [comment]
Yeah sure let's do that.

**Comment by xens** [comment]
Here you go !
